# Generated by Django 4.0 on 2022-01-28 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=900, verbose_name='نام ')),
                ('email', models.CharField(max_length=900, verbose_name='نام ')),
                ('message', models.TextField(verbose_name='پیام ')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تماس با من',
            },
        ),
    ]
