# Generated by Django 4.0 on 2022-01-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=900, null=True, verbose_name='عنوان پروژه ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات پروژه ')),
                ('photo', models.ImageField(upload_to='Projectphotos')),
                ('link', models.CharField(max_length=900, verbose_name='لینک پروژه ')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'پروژه ها',
            },
        ),
    ]
