# Generated by Django 4.0 on 2022-01-28 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='description',
        ),
    ]
