# Generated by Django 4.0 on 2022-01-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=900, null=True, verbose_name='نام و نام خانوداگی ')),
                ('title', models.CharField(blank=True, max_length=900, null=True, verbose_name='عنوان وب سایت ')),
                ('jobside', models.CharField(blank=True, max_length=900, null=True, verbose_name='سمت شغلی - مثال back end ')),
                ('email', models.CharField(blank=True, max_length=900, null=True, verbose_name='ایمیل ')),
                ('phone', models.CharField(blank=True, max_length=900, null=True, verbose_name='تلفن ')),
                ('instagram', models.CharField(blank=True, max_length=900, null=True, verbose_name='اینستاگرام ')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
    ]
