# Generated by Django 4.0 on 2022-01-28 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='age',
            field=models.CharField(blank=True, max_length=900, null=True, verbose_name='سن '),
        ),
    ]
