# Generated by Django 4.0 on 2022-01-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=900, verbose_name='عنوان مهارت')),
                ('percentage', models.IntegerField(default=0, verbose_name='درصد بلد بودن مهارت - مثال 30')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'مهارت ها',
            },
        ),
    ]
